const data= {
    products:[
        {
            _id:"1",
            name:"Air Jordan 1 KO 'Chicago'",
            category: 'Shoes',
            image:'/images/jordan1.png',
            price: 170,
            countInStock: 10,
            rating: 5,
            brand: 'Jordan',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"2",
            name:"Air Jordan 4  'University Blue'",
            category: 'Shoes',
            image:'/images/jordan2.png',
            price: 200,
            countInStock: 5,
            rating: 4,
            brand: 'Jordan',
            numReview: 15,
            description: 'High Quality Shoes'
        },
        {
            _id:"3",
            name:"Air Jordan 6  'Cactus Jack'",
            category: 'Shoes',
            image:'/images/jordan3.png',
            price: 250,
            countInStock: 0,
            rating: 5,
            brand: 'Jordan',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"4",
            name:"Air Jordan 5  'Raging Bull'",
            category: 'Shoes',
            image:'/images/jordan4.png',
            price: 190,
            countInStock: 7,
            rating: 3.5,
            brand: 'Jordan',
            numReview: 10,
            description: 'High Quality Shoes'
        },
        {
            _id:"5",
            name:"Air Jordan 2 Low x Off-White",
            category: 'Shoes',
            image:'/images/jordan5.png',
            price: 650,
            countInStock: 14,
            rating: 2,
            brand: 'Jordan',
            numReview: 40,
            description: 'High Quality Shoes'
        },
        {
            _id:"6",
            name:"Air Jordan 7 Retro-White",
            category: 'Shoes',
            image:'/images/jordan6.png',
            price: 90,
            countInStock: 10,
            rating: 3,
            brand: 'Jordan',
            numReview: 5,
            description: 'High Quality Shoes'
        },
        {
            _id:"7",
            name:"Air Jordan 7 CC White/Mettalic",
            category: 'Shoes',
            image:'/images/jordan7.png',
            price: 250,
            countInStock: 4,
            rating: 4.5,
            brand: 'Jordan',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"8",
            name:"Air Jordan 9 'Gym Red'",
            category: 'Shoes',
            image:'/images/jordan8.png',
            price: 180,
            countInStock: 10,
            rating: 3,
            brand: 'Jordan',
            numReview: 15,
            description: 'High Quality Shoes'
        },
        {
            _id:"9",
            name:"Air Jordan 9 'Midnight Navy'",
            category: 'Shoes',
            image:'/images/jordan9.png',
            price: 190,
            countInStock: 9,
            rating: 5,
            brand: 'Jordan',
            numReview: 15,
            description: 'High Quality Shoes'
        },
        {
            _id:"10",
            name:"Air Jordan 5 'Blue Bird'",
            category: 'Shoes',
            image:'/images/jordan10.png',
            price: 190,
            countInStock: 23,
            rating: 3.5,
            brand: 'Jordan',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"11",
            name:"Nike Air Max 270 G",
            category: 'Shoes',
            image:'/images/nike1.png',
            price: 150,
            countInStock: 19,
            rating: 5,
            brand: 'Nike',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"12",
            name:"Nike Air Max'",
            category: 'Shoes',
            image:'/images/nike2.png',
            price: 120,
            countInStock: 5,
            rating: 3,
            brand: 'Nike',
            numReview: 15,
            description: 'High Quality Shoes'
        },
        {
            _id:"13",
            name:"Nike AF 1/1 Men",
            category: 'Shoes',
            image:'/images/nike3.png',
            price: 130,
            countInStock: 12,
            rating: 2,
            brand: 'Nike',
            numReview: 10,
            description: 'High Quality Shoes'
        },
        {
            _id:"14",
            name:"Kobe 6 Protro 'All Star'",
            category: 'Shoes',
            image:'/images/nike4.png',
            price: 180,
            countInStock: 0,
            rating: 5,
            brand: 'Nike',
            numReview: 30,
            description: 'High Quality Shoes'
        },
        {
            _id:"15",
            name:"Kobe 5 Protro 'Hall of Fame'",
            category: 'Shoes',
            image:'/images/nike5.png',
            price: 225,
            countInStock: 17,
            rating: 4.5,
            brand: 'Nike',
            numReview: 50,
            description: 'High Quality Shoes'
        },
        {
            _id:"16",
            name:"Kobe 5 Protro '5 Rings'",
            category: 'Shoes',
            image:'/images/nike6.png',
            price: 180,
            countInStock: 10,
            rating: 5,
            brand: 'Nike',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"17",
            name:"Nike Lebron 9",
            category: 'Shoes',
            image:'/images/nike7.png',
            price: 170,
            countInStock: 15,
            rating: 4.5,
            brand: 'Nike',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"18",
            name:"Nike AF 1/1 Men 'Blue'",
            category: 'Shoes',
            image:'/images/nike8.png',
            price: 130,
            countInStock: 5,
            rating: 3,
            brand: 'Nike',
            numReview: 10,
            description: 'High Quality Shoes'
        },
        {
            _id:"19",
            name:"Nike Lebron 8 V/2 'Treasure Blue'",
            category: 'Shoes',
            image:'/images/nike9.png',
            price: 180,
            countInStock: 20,
            rating: 5,
            brand: 'Nike',
            numReview: 20,
            description: 'High Quality Shoes'
        },
        {
            _id:"20",
            name:"Air Max Lebron 7 'History'",
            category: 'Shoes',
            image:'/images/nike10.png',
            price: 200,
            countInStock: 10,
            rating: 4.5,
            brand: 'Nike',
            numReview: 20,
            description: 'High Quality Shoes'
        },

    ]
}
export default data;